### ISSUE TITLE
Redundant code for key actions

### ISSUE THREAD

**Issue by suint** [cisc275/lab-06-07-11-16#4]
Key events use repetitive code

**Comment by WanqiLiang** [comment]
pics = new HashMap<String, BufferedImage[][]>();
		
		String[] keyWord = new String[] {"forward","fire","jump"};
		
		for(String S:keyWord) {
		//add value to the pics hash map for the running state
		BufferedImage[][] img = new BufferedImage[8][10];
		pics.put(S, img);
		for (int h = 0; h < 8; h++) {
			Direction dirk = Direction.atIndex(h);
			BufferedImage imgS = createImage("images/orc/orc_"+S+"_"+dirk.getName()+".png");
			if(S == "forward") {
				frameCount = 10;
			}
			else if(S == "fire") {
				frameCount = 4 ;
			}
			else {
				frameCount = 8;
			}
			for(int i = 0; i <  frameCount; i++)
				img[h][i] = imgS.getSubimage(imgWidth*i, 0, imgWidth, imgHeight);
		}
		}

I tried something like this, is there a better way?
